# Identifiant unique (celui que vous avez défini dans l'interface Sonar)
sonar.projectKey=translation-app-front

# Paramètres de connexion (optionnel si vous les passez en ligne de commande, mais pratique)
sonar.host.url=http://localhost:9000

# Quels fichiers scanner ?
sonar.sources=src
sonar.exclusions=node_modules/**, coverage/**, dist/**
sonar.cpd.exclusions=src/app/globals.css
